#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 27 13:56:53 CET 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim agc_clock_tb_behav -key {Behavioral:sim_1:Functional:agc_clock_tb} -tclbatch agc_clock_tb.tcl -protoinst "protoinst_files/zynq_ps.protoinst" -log simulate.log"
xsim agc_clock_tb_behav -key {Behavioral:sim_1:Functional:agc_clock_tb} -tclbatch agc_clock_tb.tcl -protoinst "protoinst_files/zynq_ps.protoinst" -log simulate.log

