set_property -dict { PACKAGE_PIN Y6  IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { clk }];
set_property -dict { PACKAGE_PIN J22 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { prop_clk }];
set_property -dict { PACKAGE_PIN J21 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { prop_clk_locked }];
set_property -dict { PACKAGE_PIN L22 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { agc_clk }];
set_property -dict { PACKAGE_PIN L21 IOSTANDARD LVCMOS33 PULLDOWN true}         [get_ports { reset }];
set_property -dict { PACKAGE_PIN H20 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { CLK }];
set_property -dict { PACKAGE_PIN F22 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT01 }];
set_property -dict { PACKAGE_PIN C22 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT02 }];
set_property -dict { PACKAGE_PIN B22 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT03 }];
set_property -dict { PACKAGE_PIN B20 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT04 }];
set_property -dict { PACKAGE_PIN A19 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT05 }];
set_property -dict { PACKAGE_PIN A17 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT06 }];
set_property -dict { PACKAGE_PIN B15 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT07 }];
set_property -dict { PACKAGE_PIN D17 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT08 }];
set_property -dict { PACKAGE_PIN D21 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT09 }];
set_property -dict { PACKAGE_PIN F17 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT10 }];
set_property -dict { PACKAGE_PIN P18 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT11 }];
set_property -dict { PACKAGE_PIN K18 IOSTANDARD LVCMOS33 DRIVE 4 }              [get_ports { MT12 }];
