# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/rzinkstok/agc_clock/agc_clock.cache/wt [current_project]
set_property parent.project_path /home/rzinkstok/agc_clock/agc_clock.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part numato.com:styx:part0:1.0 [current_project]
set_property ip_output_repo /home/rzinkstok/agc_clock/agc_clock.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/new/a02_timer.v
  /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/new/agc_clock_divisor.v
  /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/new/nor_3.v
  /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/bd/zynq_ps/hdl/zynq_ps_wrapper.v
  /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/new/agc_clock.v
}
add_files /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/bd/zynq_ps/zynq_ps.bd
set_property used_in_implementation false [get_files -all /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/bd/zynq_ps/ip/zynq_ps_processing_system7_0_0/zynq_ps_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/bd/zynq_ps/zynq_ps_ooc.xdc]

read_ip -quiet /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/ip/prop_clock_divisor/prop_clock_divisor.xci
set_property used_in_implementation false [get_files -all /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/ip/prop_clock_divisor/prop_clock_divisor_board.xdc]
set_property used_in_implementation false [get_files -all /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/ip/prop_clock_divisor/prop_clock_divisor.xdc]
set_property used_in_implementation false [get_files -all /home/rzinkstok/agc_clock/agc_clock.srcs/sources_1/ip/prop_clock_divisor/prop_clock_divisor_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/rzinkstok/agc_clock/agc_clock.srcs/constrs_1/new/agc_clock.xdc
set_property used_in_implementation false [get_files /home/rzinkstok/agc_clock/agc_clock.srcs/constrs_1/new/agc_clock.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top agc_clock -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef agc_clock.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file agc_clock_utilization_synth.rpt -pb agc_clock_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
