# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/agc_clock.xdc

# Block Designs: bd/zynq_ps/zynq_ps.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps || ORIG_REF_NAME==zynq_ps} -quiet] -quiet

# IP: bd/zynq_ps/ip/zynq_ps_processing_system7_0_0/zynq_ps_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps_processing_system7_0_0 || ORIG_REF_NAME==zynq_ps_processing_system7_0_0} -quiet] -quiet

# XDC: /home/rzinkstok/development/agc_clock/agc_clock.gen/sources_1/bd/zynq_ps/zynq_ps_ooc.xdc
