# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rzinkstok/development/agc_clock/agc_clock.srcs/sources_1/ip/prop_clock_divisor/prop_clock_divisor.xci
# IP: The module: 'prop_clock_divisor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rzinkstok/development/agc_clock/agc_clock.gen/sources_1/ip/prop_clock_divisor/prop_clock_divisor_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divisor'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/rzinkstok/development/agc_clock/agc_clock.gen/sources_1/ip/prop_clock_divisor/prop_clock_divisor.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divisor'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/rzinkstok/development/agc_clock/agc_clock.gen/sources_1/ip/prop_clock_divisor/prop_clock_divisor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divisor'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/rzinkstok/development/agc_clock/agc_clock.srcs/sources_1/ip/prop_clock_divisor/prop_clock_divisor.xci
# IP: The module: 'prop_clock_divisor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rzinkstok/development/agc_clock/agc_clock.gen/sources_1/ip/prop_clock_divisor/prop_clock_divisor_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divisor'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/rzinkstok/development/agc_clock/agc_clock.gen/sources_1/ip/prop_clock_divisor/prop_clock_divisor.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divisor'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/rzinkstok/development/agc_clock/agc_clock.gen/sources_1/ip/prop_clock_divisor/prop_clock_divisor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prop_clock_divisor'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
